{{- $nameprefix := include "im.nameprefix" . }}
{{- $tlssecret := .Values.tlssecret }}
{{- $tlssecretallowedns := .Values.tlssecret.allowtlssecretaccessto }}
{{- range $tlssecretallowedns }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .ns }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginxingress-secretprovider
  namespace: {{ .ns }}
spec:
  provider: azure
  secretObjects:
    - data: 
      - objectName: {{ $tlssecret.certname }}
        key: tls.key
      - objectName: {{ $tlssecret.certname }}
        key: tls.crt
      secretName: nginx-tls-secret
      type: kubernetes.io/tls
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: {{ $tlssecret.uassignid }}
    keyvaultName: {{ $tlssecret.keyvaultname }}
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: {{ $tlssecret.certname }}
          objectType: secret
    tenantId: {{ $tlssecret.keyvaulttenantId }}
{{- end }}            
