apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceaccount.clientid }} 
  labels:
    azure.workload.identity/use: "true"
  name: {{ include "im.nameprefix" . }}-serviceaccount
  namespace: {{ .Values.serviceaccount.namespace }} 
